-- MySQL Script generated by MySQL Workbench
-- Fri Jan  5 19:14:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Menu_Electronico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Menu_Electronico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Menu_Electronico` DEFAULT CHARACTER SET utf8 ;
USE `Menu_Electronico` ;

-- -----------------------------------------------------
-- Table `Menu_Electronico`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Menu_Electronico`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Menu_Electronico`.`AreaOperativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Menu_Electronico`.`AreaOperativa` (
  `idArea` INT NOT NULL AUTO_INCREMENT,
  `Area` VARCHAR(45) NULL,
  PRIMARY KEY (`idArea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Menu_Electronico`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Menu_Electronico`.`Productos` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Descripcion` VARCHAR(200) NULL DEFAULT NULL,
  `Precio` INT NULL DEFAULT NULL,
  `Disponible` TINYINT NULL DEFAULT NULL,
  `idCategoria` INT NOT NULL,
  `idSector` INT NOT NULL,
  `Imagen1` VARCHAR(100) NULL,
  `Imagen2` VARCHAR(100) NULL,
  `Imagen3` VARCHAR(100) NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Productos_Categoria_idx` (`idCategoria` ASC),
  INDEX `fk_Productos_Sector1_idx` (`idSector` ASC),
  CONSTRAINT `fk_Productos_Categoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `Menu_Electronico`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Sector1`
    FOREIGN KEY (`idSector`)
    REFERENCES `Menu_Electronico`.`AreaOperativa` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Menu_Electronico`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Menu_Electronico`.`Usuarios` (
  `idUsuario` INT NOT NULL,
  `Usuario` VARCHAR(45) NULL,
  `Clave` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Menu_Electronico`.`Camareros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Menu_Electronico`.`Camareros` (
  `idCamarero` INT NOT NULL,
  `Camarero` VARCHAR(45) NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idCamarero`),
  INDEX `fk_Camareros_Usuarios1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Camareros_Usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Menu_Electronico`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Menu_Electronico`.`Mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Menu_Electronico`.`Mesa` (
  `idMesa` INT NOT NULL AUTO_INCREMENT,
  `Numero_Mesa` INT NULL DEFAULT NULL,
  `idCamarero` INT NOT NULL,
  PRIMARY KEY (`idMesa`),
  INDEX `fk_Mesa_Camareros1_idx` (`idCamarero` ASC),
  CONSTRAINT `fk_Mesa_Camareros1`
    FOREIGN KEY (`idCamarero`)
    REFERENCES `Menu_Electronico`.`Camareros` (`idCamarero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Menu_Electronico`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Menu_Electronico`.`Clientes` (
  `idCliente` INT NOT NULL,
  `RazonSocial` VARCHAR(45) NULL,
  `CUIT` VARCHAR(11) NULL,
  `CondicionIVA` VARCHAR(15) NULL,
  `Domicilio` VARCHAR(45) NULL,
  `Email` VARCHAR(50) NULL,
  `Telefono` VARCHAR(15) NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Clientes_Usuarios1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Clientes_Usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Menu_Electronico`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Menu_Electronico`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Menu_Electronico`.`Pedidos` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `idMesa` INT NOT NULL,
  `Fecha` DATETIME NULL,
  `HoraPedido` DATETIME NULL,
  `HoraEntrega` DATETIME NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Mesa1_idx` (`idMesa` ASC),
  INDEX `fk_Pedidos_Clientes1_idx` (`idCliente` ASC),
  CONSTRAINT `fk_Pedido_Mesa1`
    FOREIGN KEY (`idMesa`)
    REFERENCES `Menu_Electronico`.`Mesa` (`idMesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Clientes1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `Menu_Electronico`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Menu_Electronico`.`ItemsPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Menu_Electronico`.`ItemsPedido` (
  `idPedido` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `cant` INT NULL,
  `subTotal` REAL NULL,
  INDEX `fk_ItemsPedido_Productos1_idx` (`idProducto` ASC),
  CONSTRAINT `fk_ItemsPedido_Pedido1`
    FOREIGN KEY (`idPedido`)
    REFERENCES `Menu_Electronico`.`Pedidos` (`idMesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItemsPedido_Productos1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `Menu_Electronico`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
