package Modelo;
// Generated 29-dic-2017 16:44:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Camareros generated by hbm2java
 */
public class Camareros  implements java.io.Serializable {


     private int idCamarero;
     private Usuarios usuarios;
     private String camarero;
     private Set mesas = new HashSet(0);

    public Camareros() {
    }

	
    public Camareros(int idCamarero, Usuarios usuarios) {
        this.idCamarero = idCamarero;
        this.usuarios = usuarios;
    }
    public Camareros(int idCamarero, Usuarios usuarios, String camarero, Set mesas) {
       this.idCamarero = idCamarero;
       this.usuarios = usuarios;
       this.camarero = camarero;
       this.mesas = mesas;
    }
   
    public int getIdCamarero() {
        return this.idCamarero;
    }
    
    public void setIdCamarero(int idCamarero) {
        this.idCamarero = idCamarero;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getCamarero() {
        return this.camarero;
    }
    
    public void setCamarero(String camarero) {
        this.camarero = camarero;
    }
    public Set getMesas() {
        return this.mesas;
    }
    
    public void setMesas(Set mesas) {
        this.mesas = mesas;
    }




}


