package Modelo;
// Generated 29-dic-2017 16:44:04 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pedidos generated by hbm2java
 */
public class Pedidos  implements java.io.Serializable {


     private Integer idPedido;
     private Clientes clientes;
     private Mesa mesa;
     private Date fecha;
     private Date horaPedido;
     private Date horaEntrega;

    public Pedidos() {
    }

	
    public Pedidos(Clientes clientes, Mesa mesa) {
        this.clientes = clientes;
        this.mesa = mesa;
    }
    public Pedidos(Clientes clientes, Mesa mesa, Date fecha, Date horaPedido, Date horaEntrega) {
       this.clientes = clientes;
       this.mesa = mesa;
       this.fecha = fecha;
       this.horaPedido = horaPedido;
       this.horaEntrega = horaEntrega;
    }
   
    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Mesa getMesa() {
        return this.mesa;
    }
    
    public void setMesa(Mesa mesa) {
        this.mesa = mesa;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHoraPedido() {
        return this.horaPedido;
    }
    
    public void setHoraPedido(Date horaPedido) {
        this.horaPedido = horaPedido;
    }
    public Date getHoraEntrega() {
        return this.horaEntrega;
    }
    
    public void setHoraEntrega(Date horaEntrega) {
        this.horaEntrega = horaEntrega;
    }




}


