package Modelo;
// Generated 29-dic-2017 16:44:04 by Hibernate Tools 4.3.1



/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer idProducto;
     private Areaoperativa areaoperativa;
     private Categoria categoria;
     private String nombre;
     private String descripcion;
     private Integer precio;
     private Byte disponible;
     private String imagen1;
     private String imagen2;
     private String imagen3;

    public Productos() {
    }

	
    public Productos(Areaoperativa areaoperativa, Categoria categoria) {
        this.areaoperativa = areaoperativa;
        this.categoria = categoria;
    }
    public Productos(Areaoperativa areaoperativa, Categoria categoria, String nombre, String descripcion, Integer precio, Byte disponible, String imagen1, String imagen2, String imagen3) {
       this.areaoperativa = areaoperativa;
       this.categoria = categoria;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precio = precio;
       this.disponible = disponible;
       this.imagen1 = imagen1;
       this.imagen2 = imagen2;
       this.imagen3 = imagen3;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Areaoperativa getAreaoperativa() {
        return this.areaoperativa;
    }
    
    public void setAreaoperativa(Areaoperativa areaoperativa) {
        this.areaoperativa = areaoperativa;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }
    public Byte getDisponible() {
        return this.disponible;
    }
    
    public void setDisponible(Byte disponible) {
        this.disponible = disponible;
    }
    public String getImagen1() {
        return this.imagen1;
    }
    
    public void setImagen1(String imagen1) {
        this.imagen1 = imagen1;
    }
    public String getImagen2() {
        return this.imagen2;
    }
    
    public void setImagen2(String imagen2) {
        this.imagen2 = imagen2;
    }
    public String getImagen3() {
        return this.imagen3;
    }
    
    public void setImagen3(String imagen3) {
        this.imagen3 = imagen3;
    }




}


