package Modelo;
// Generated 29-dic-2017 16:44:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int idUsuario;
     private String usuario;
     private String clave;
     private Set camareroses = new HashSet(0);
     private Set clienteses = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuarios(int idUsuario, String usuario, String clave, Set camareroses, Set clienteses) {
       this.idUsuario = idUsuario;
       this.usuario = usuario;
       this.clave = clave;
       this.camareroses = camareroses;
       this.clienteses = clienteses;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Set getCamareroses() {
        return this.camareroses;
    }
    
    public void setCamareroses(Set camareroses) {
        this.camareroses = camareroses;
    }
    public Set getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set clienteses) {
        this.clienteses = clienteses;
    }




}


